spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kingsleo/springcloud-config-repo
          username: 76727998@qq.com
          password: *****
          basedir: /Users/kingsleo/Sites/luna/workspace/SpringCloud/config/basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"